spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/hr_sample
    username: postgres
    password: 123456

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

mybatis:
  configuration:
    map-underscore-to-camel-case: true


